"""add campus and semester to schedule models

Revision ID: 2f6eab67ec2a
Revises: d4e5f6a7b8c9
Create Date: 2025-11-20 18:54:47.354983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f6eab67ec2a'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_activities', sa.Column('campus', sa.String(length=100), nullable=True))
    op.add_column('schedule_activities', sa.Column('semester', sa.String(length=100), nullable=True))
    op.add_column('schedule_courses', sa.Column('campus', sa.String(length=100), nullable=True))
    op.add_column('schedule_courses', sa.Column('semester', sa.String(length=100), nullable=True))
    op.add_column('schedules', sa.Column('campus', sa.String(length=100), nullable=True))
    op.add_column('schedules', sa.Column('semester', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'semester')
    op.drop_column('schedules', 'campus')
    op.drop_column('schedule_courses', 'semester')
    op.drop_column('schedule_courses', 'campus')
    op.drop_column('schedule_activities', 'semester')
    op.drop_column('schedule_activities', 'campus')
    # ### end Alembic commands ###
