"""refactor_courses_to_shared_table

Revision ID: 440cd41109f8
Revises: bc2ebe684502
Create Date: 2025-11-21 01:24:57.348568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '440cd41109f8'
down_revision: Union[str, Sequence[str], None] = 'bc2ebe684502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('course_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('teacher_name', sa.String(length=255), nullable=False),
    sa.Column('section_id', sa.String(length=50), nullable=True),
    sa.Column('times_days', sa.String(length=255), nullable=True),
    sa.Column('campus', sa.String(length=100), nullable=True),
    sa.Column('semester', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('difficulty_rating', sa.Float(), nullable=True),
    sa.Column('mode', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('rating_details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('schedule_courses')
    op.add_column('schedules', sa.Column('section_ids', sa.JSON(), nullable=True))
    op.execute("UPDATE schedules SET section_ids = '[]'")
    op.alter_column('schedules', 'section_ids', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'section_ids')
    op.create_table('schedule_courses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('section_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('times_days', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('teacher_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('campus', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('semester', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('difficulty_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mode', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('rating_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('schedule_courses_schedule_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('schedule_courses_pkey'))
    )
    op.drop_table('courses')
    # ### end Alembic commands ###
