"""add_difficulty_score_and_num_classes_to_schedules

Revision ID: 51c76e737027
Revises: 7aafd7c0341a
Create Date: 2025-11-21 05:02:13.157677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c76e737027'
down_revision: Union[str, Sequence[str], None] = '7aafd7c0341a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('difficulty_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'difficulty_score')
    # ### end Alembic commands ###
