"""Restructure database: update courses composite key, add schedule scoring fields, create junction table

Revision ID: 61a38f560b82
Revises: 8bee70843581
Create Date: 2025-11-05 20:15:05.168751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61a38f560b82'
down_revision: Union[str, Sequence[str], None] = '8bee70843581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Drop foreign key from schedule_courses to courses
    op.drop_constraint('schedule_courses_course_id_fkey', 'schedule_courses', type_='foreignkey')

    # Step 2: Restructure courses table (drop old primary key, add new columns)
    op.execute('ALTER TABLE courses DROP CONSTRAINT IF EXISTS courses_pkey')
    op.add_column('courses', sa.Column('course_id', sa.String(length=50), nullable=True))
    op.add_column('courses', sa.Column('teacher_name', sa.String(length=255), nullable=True))
    op.add_column('courses', sa.Column('course_rating', sa.JSON(), nullable=True))

    # Migrate data: copy 'id' to 'course_id' for existing rows
    op.execute("UPDATE courses SET course_id = id, teacher_name = 'Unknown', course_rating = '{}'::json")

    # Make new columns non-nullable
    op.alter_column('courses', 'course_id', nullable=False)
    op.alter_column('courses', 'teacher_name', nullable=False)
    op.alter_column('courses', 'course_rating', nullable=False)

    # Drop old columns
    op.drop_column('courses', 'name')
    op.drop_column('courses', 'id')
    op.drop_column('courses', 'summary')
    op.drop_column('courses', 'credit_hours')
    op.drop_column('courses', 'score')
    op.drop_column('courses', 'rigor')

    # Add new composite primary key
    op.create_primary_key('courses_pkey', 'courses', ['course_id', 'teacher_name'])

    # Step 3: Add teacher_name to schedule_courses
    op.add_column('schedule_courses', sa.Column('teacher_name', sa.String(length=255), nullable=True))
    op.execute("UPDATE schedule_courses SET teacher_name = 'Unknown'")
    op.alter_column('schedule_courses', 'teacher_name', nullable=False)

    # Step 4: Update schedules table
    op.add_column('schedules', sa.Column('total_credit_hours', sa.Integer(), nullable=True))
    op.add_column('schedules', sa.Column('num_classes', sa.Integer(), nullable=True))
    op.add_column('schedules', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('schedules', sa.Column('adjusted_difficulty', sa.Integer(), nullable=True))
    op.add_column('schedules', sa.Column('adjusted_assessment_intensity', sa.Integer(), nullable=True))
    op.add_column('schedules', sa.Column('adjusted_project_intensity', sa.Integer(), nullable=True))
    op.add_column('schedules', sa.Column('time_load', sa.Float(), nullable=True))
    op.add_column('schedules', sa.Column('adjusted_rigor', sa.Integer(), nullable=True))
    op.add_column('schedules', sa.Column('constraints', sa.Text(), nullable=True))
    op.add_column('schedules', sa.Column('confidence', sa.Float(), nullable=True))
    op.drop_column('schedules', 'difficulty_score')

    # Step 5: Now create schedule_course_links with proper foreign keys
    op.create_table('schedule_course_links',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(length=50), nullable=False),
    sa.Column('teacher_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['course_id', 'teacher_name'], ['courses.course_id', 'courses.teacher_name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_id', 'course_id', 'teacher_name')
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('difficulty_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('schedules', 'confidence')
    op.drop_column('schedules', 'constraints')
    op.drop_column('schedules', 'adjusted_rigor')
    op.drop_column('schedules', 'time_load')
    op.drop_column('schedules', 'adjusted_project_intensity')
    op.drop_column('schedules', 'adjusted_assessment_intensity')
    op.drop_column('schedules', 'adjusted_difficulty')
    op.drop_column('schedules', 'summary')
    op.drop_column('schedules', 'num_classes')
    op.drop_column('schedules', 'total_credit_hours')
    op.create_foreign_key(op.f('schedule_courses_course_id_fkey'), 'schedule_courses', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_column('schedule_courses', 'teacher_name')
    op.add_column('courses', sa.Column('rigor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('credit_hours', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('courses', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('courses', 'course_rating')
    op.drop_column('courses', 'teacher_name')
    op.drop_column('courses', 'course_id')
    op.drop_table('schedule_course_links')
    # ### end Alembic commands ###
