"""group_grading_details_to_json

Revision ID: 7aafd7c0341a
Revises: 440cd41109f8
Create Date: 2025-11-21 01:43:54.012410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aafd7c0341a'
down_revision: Union[str, Sequence[str], None] = '440cd41109f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('grading_details', sa.JSON(), nullable=True))
    op.drop_column('schedules', 'adjusted_difficulty')
    op.drop_column('schedules', 'confidence')
    op.drop_column('schedules', 'time_load')
    op.drop_column('schedules', 'adjusted_rigor')
    op.drop_column('schedules', 'adjusted_assessment_intensity')
    op.drop_column('schedules', 'adjusted_project_intensity')
    op.drop_column('schedules', 'summary')
    op.drop_column('schedules', 'constraints')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('constraints', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('schedules', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('schedules', sa.Column('adjusted_project_intensity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('schedules', sa.Column('adjusted_assessment_intensity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('schedules', sa.Column('adjusted_rigor', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('schedules', sa.Column('time_load', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('schedules', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('schedules', sa.Column('adjusted_difficulty', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('schedules', 'grading_details')
    # ### end Alembic commands ###
