"""add_title_to_schedule_activities

Revision ID: a3be02d5d70e
Revises: 2f6eab67ec2a
Create Date: 2025-11-20 19:28:16.746351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3be02d5d70e'
down_revision: Union[str, Sequence[str], None] = '2f6eab67ec2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_activities', sa.Column('title', sa.String(length=255), nullable=False))
    op.alter_column('schedule_activities', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule_activities', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('schedule_activities', 'title')
    # ### end Alembic commands ###
