"""add_rating_details_to_schedule_course

Revision ID: c8b1b1522597
Revises: e0e4d2e0c0e8
Create Date: 2025-11-21 00:45:49.983008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8b1b1522597'
down_revision: Union[str, Sequence[str], None] = 'e0e4d2e0c0e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_courses', sa.Column('rating_details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_courses', 'rating_details')
    # ### end Alembic commands ###
