"""simplify_schedule_schema_remove_courses_table

Revision ID: e0e4d2e0c0e8
Revises: c9e5e940dbba
Create Date: 2025-11-21 00:26:24.619606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0e4d2e0c0e8'
down_revision: Union[str, Sequence[str], None] = 'c9e5e940dbba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_course_links')
    op.drop_table('courses')
    op.add_column('schedule_courses', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('schedule_courses', sa.Column('type', sa.String(length=50), nullable=True))
    op.add_column('schedule_courses', sa.Column('difficulty_rating', sa.Float(), nullable=True))
    op.add_column('schedule_courses', sa.Column('mode', sa.String(length=50), nullable=True))
    op.add_column('schedule_courses', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_courses', 'status')
    op.drop_column('schedule_courses', 'mode')
    op.drop_column('schedule_courses', 'difficulty_rating')
    op.drop_column('schedule_courses', 'type')
    op.drop_column('schedule_courses', 'title')
    op.create_table('courses',
    sa.Column('course_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('teacher_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('course_rating', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('courses_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='courses_pkey'),
    sa.UniqueConstraint('course_id', 'teacher_name', name='uq_course_teacher', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('schedule_course_links',
    sa.Column('schedule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('teacher_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id', 'teacher_name'], ['courses.course_id', 'courses.teacher_name'], name=op.f('schedule_course_links_course_id_teacher_name_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('schedule_course_links_schedule_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_id', 'course_id', 'teacher_name', name=op.f('schedule_course_links_pkey'))
    )
    # ### end Alembic commands ###
